# Usa una imagen base de Node.js para construir la aplicación
FROM node:18 AS build

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos package.json y package-lock.json (si los tienes) al contenedor
COPY package*.json ./

# Instala las dependencias del frontend
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Construye la aplicación para producción
RUN npm run build

# Usa una imagen ligera de Nginx para servir el frontend
FROM nginx:alpine

# Copia los archivos de build al directorio de Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expone el puerto por donde se servirá la app
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
